### PR TITLE
Allow setting options for HTTP Client.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Review by anhtuank7c — APPROVED** [review]
Thank you

**Comment by ADmad** [comment]
No problem, can you please make a new release? :slightly_smiling_face:

**Comment by anhtuank7c** [comment]
Sure, Please check new version `2.0.5`

**Comment by ADmad** [comment]
@anhtuank7c Packagist still shows `2.0.4` as the latest release https://packagist.org/packages/crabstudio/recaptcha. It should have updated by now. Maybe the packagist hook has been messed up since you moved the repo under another GH account. Try re-setting the packagist hook.

**Comment by anhtuank7c** [comment]
The packagist still work well, please help to update again.

screen shot 2017-10-06 at 11 57 38 pm

**Comment by ADmad** [comment]
Yes, it's updated now.  Guess i was impatient or it took longer than usual. Sorry for the false alarm. Everything seems fine.

**Comment by anhtuank7c** [comment]
@ADmad I am now focusing on `React Native`.
CakePHP is awesome, thank for your help.

**Pull request merged**
